/**
 * SUNSHIP TAILED — GENERATED by tools/gen-sunship-tailed.mjs. Do not hand-edit.
 *
 * The Sunship with its Smart Tail DEPLOYED: the aero fairing picked up at
 * 80% of the envelope, profile exponent 0.8, extending 216 m beyond it.
 *
 * WHAT THIS BODY ACTUALLY IS (r20 finding, 2026-08-19 — earlier wording
 * here overstated it): NOT the Sunship's own surface with a fairing added.
 * The generator takes the hull's cross-sectional AREA at each station,
 * converts it to an equal-area CIRCLE, grafts the fairing, and lathes the
 * whole body. So this is an AXISYMMETRIC EQUAL-AREA SURROGATE of
 * hull+fairing. A circle is the minimum perimeter for a given area, so the
 * surrogate can UNDERSTATE wetted area and therefore friction — which is
 * ~44% of the resulting Cd (0.0095 of 0.0215). Attachment is
 * radius-continuous only; the slope is not matched.
 *
 * PAIRS WITH the bare record in presetDynamics.js — the tail RETRACTS, so
 * the ship has two geometric states and the Smart Tail toggle selects
 * between them. The bare record is untouched.
 *
 * envelopeFraction: the user's "ship length" is the ENVELOPE. Scale this
 * record by lengthM / envelopeFraction so the ENVELOPE lands on the
 * slider's number and the fairing extends beyond it.
 */
export const SUNSHIP_TAILED = Object.freeze({
  aeroObj: 'lab/sunship-tail-aerohull-candidate.obj',
  objSha256: "d371cf10a9bbebbbe09402bbfd3d39ecb8bf798b8ffafcae55de63712dc4ddf4",
  defaultAxis: '+X',
  envelopeFraction: 0.581395,
  deployedOverEnvelope: 1.720000,
  raw: Object.freeze({"extents":[516,226.01608,226.01608],"frontalRaw":{"X":40056.28811559161,"Y":74375.21770725,"Z":74375.21770725003},"wettedRaw":253918.88171342973,"hullRaw":254856.020877061,"meshRaw":253918.88171342973,"wettedSource":"mesh","volumeRaw":10218809.399139639,"volumeSource":"convex-envelope","warnings":[]}),
  proxies: Object.freeze({"+X":{"proxy":0.16446151218799673,"cls":"rounded","triggers":{"softFore":0.0016734936932571115,"softAft":0.16446151218799673,"terminalBaseFrac":0.00039896269698783165,"rawRatio":1,"shoulder":0.09122170121587013},"oddFraction":0.001195457262402869},"-X":{"proxy":0.7717201018309247,"cls":"pinned","triggers":{"softFore":0,"softAft":0.7717201018309247,"terminalBaseFrac":0.011569918212647117,"rawRatio":1,"shoulder":0.13809326300043898},"oddFraction":0.001195457262402869},"+Y":{"proxy":0.9205355263599778,"cls":"rounded","triggers":{"softFore":0.024323573522714872,"softAft":0.9205355263599778,"terminalBaseFrac":0.018351214003387916,"rawRatio":1,"shoulder":0.12538825886162674},"oddFraction":0},"-Y":{"proxy":0.9205355263599778,"cls":"rounded","triggers":{"softFore":0.024323573522714872,"softAft":0.9205355263599778,"terminalBaseFrac":0.018351214003387916,"rawRatio":1,"shoulder":0.12538825886162674},"oddFraction":0},"+Z":{"proxy":0.9205355263599778,"cls":"rounded","triggers":{"softFore":0.024323573522714872,"softAft":0.9205355263599778,"terminalBaseFrac":0.018351214003387916,"rawRatio":1,"shoulder":0.12538825886162674},"oddFraction":0},"-Z":{"proxy":0.9205355263599778,"cls":"rounded","triggers":{"softFore":0.024323573522714872,"softAft":0.9205355263599778,"terminalBaseFrac":0.018351214003387916,"rawRatio":1,"shoulder":0.12538825886162674},"oddFraction":0}}),
});
