/**
 * SUNSHIP TAILED — GENERATED by tools/gen-sunship-tailed.mjs. Do not hand-edit.
 *
 * The Sunship with its Smart Tail DEPLOYED: the aero fairing picked up at
 * 80% of the envelope, profile exponent 0.8, extending 216 m beyond it.
 *
 * BUILT FROM THE HULL'S TRUE SECTION SHAPE (r20 send-back, closed
 * 2026-08-19). The previous version replaced each station's cross-
 * sectional AREA with an equal-area CIRCLE and lathed the result — an
 * axisymmetric surrogate, not the Sunship. This one samples the hull's
 * real outline r(x, theta) by plane-triangle intersection, so the body
 * keeps the Sunship's actual wider-than-tall sections, and the fairing
 * inherits that outline scaled by the profile rather than becoming a cone
 * of revolution. Cost of the correction: Cd 0.0215 -> 0.0221 (+2.8%),
 * wetted 253,919 -> 266,094 m2 (+4.8%). The surrogate was optimistic.
 *
 * Outlines are INTERPOLATED between stations, not snapped to the nearest.
 * Snapping makes the surface piecewise-constant in x, so wetted area grows
 * without bound with ring count (measured 266,518 -> 286,302 m2 from 128
 * to 1024 rings, still climbing) — the old record's wetted area was partly
 * a function of its own discretisation. Converged settings below.
 *
 * ATTACHMENT IS RADIUS-CONTINUOUS, NOT TANGENTIAL, and deliberately so.
 * Solving the profile exponent for C1 continuity with the hull gives
 * P = 2.4, and that tail is aerodynamically ruinous: proxy 0.674, Cd 0.154,
 * seven times worse. A single power law cannot be both tangent and a good
 * fairing, so P = 0.8 stays as an AERODYNAMIC choice. Earlier docs claiming
 * tangency were wrong; implementing it as claimed would have been worse.
 *
 * PAIRS WITH the bare record in presetDynamics.js — the tail RETRACTS, so
 * the ship has two geometric states and the Smart Tail toggle selects
 * between them. The bare record is untouched.
 *
 * envelopeFraction: the user's "ship length" is the ENVELOPE. Scale this
 * record by lengthM / envelopeFraction so the ENVELOPE lands on the
 * slider's number and the fairing extends beyond it.
 */
export const SUNSHIP_TAILED = Object.freeze({
  sourceHull: '3D OBJ/Sunship.obj',
  objSha256: "dee482af0af99bd01cb5002cae61c969dba114a9b2ca67e336e8a00fd18d3e64",
  defaultAxis: '+X',
  envelopeFraction: 0.581395,
  deployedOverEnvelope: 1.720000,
  raw: Object.freeze({"extents":[516,247.33588488140487,236.69474291626938],"frontalRaw":{"X":40426.61133598769,"Y":81019.33975181592,"Z":80450.57436002082},"wettedRaw":266093.95202084514,"hullRaw":268423.7706378965,"meshRaw":266093.95202084514,"wettedSource":"mesh","volumeRaw":10525010.05293453,"volumeSource":"convex-envelope","warnings":[]}),
  proxies: Object.freeze({"+X":{"proxy":0.1735452439587493,"cls":"rounded","triggers":{"softFore":0.0036899053176688524,"softAft":0.1735452439587493,"terminalBaseFrac":0.0002384642899725766,"rawRatio":1,"shoulder":0.09357293482045749},"oddFraction":0.0029719448407037564},"-X":{"proxy":0.7683405257673633,"cls":"pinned","triggers":{"softFore":0,"softAft":0.7683405257673633,"terminalBaseFrac":0.01621557171813521,"rawRatio":1,"shoulder":0.1417046907700494},"oddFraction":0.0029719448407037564},"+Y":{"proxy":0.9629465495553764,"cls":"pinned","triggers":{"softFore":0.000008417691446677932,"softAft":0.9629465495553764,"terminalBaseFrac":0.0006505334374186833,"rawRatio":1,"shoulder":0.21151156863603973},"oddFraction":0},"-Y":{"proxy":0.9620026638176553,"cls":"pinned","triggers":{"softFore":0.000008417691446677932,"softAft":0.9620026638176553,"terminalBaseFrac":0.0006505334374186833,"rawRatio":1,"shoulder":0.20897957748367502},"oddFraction":0},"+Z":{"proxy":0.8725131694491415,"cls":"pinned","triggers":{"softFore":0.2318606224064738,"softAft":0.8725131694491415,"terminalBaseFrac":0.003596624706045096,"rawRatio":1.0000000680532204,"shoulder":0.13815707226955268},"oddFraction":0},"-Z":{"proxy":0.9846125221229927,"cls":"pinned","triggers":{"softFore":0,"softAft":0.9846125221229927,"terminalBaseFrac":0.2538387052151058,"rawRatio":1,"shoulder":0.3643210684350144},"oddFraction":0}}),
});
